# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Layers
                                 A QGIS plugin
 Unterstützung bei der Erstellung von digitalen Angebotsnetzen für den Radverkehr
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Vision Velo UG (haftungsbeschränkt)
        email                : info@vision-velo.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import QgsVectorLayer, QgsCategorizedSymbolRenderer, QgsMarkerSymbol, QgsRendererCategory

class CenterLayer():
    def __init__(self, layer):
        renderer = self._createRenderer()
        layer.setRenderer(renderer)
        layer.triggerRepaint()

        self._layer = layer
    
    def _createRenderer(self, categoryField: str = "Centertype") -> QgsCategorizedSymbolRenderer:
        renderer = QgsCategorizedSymbolRenderer(categoryField)

        # Define your categories with their styles
        # Format: CenterType value, Symbol (color and size), Label
        categories = [
            ["Oberzentru", QgsMarkerSymbol.createSimple({'color': '0,0,255', 'size': '4'}), "Oberzentrum"],
            ["Grundzentr", QgsMarkerSymbol.createSimple({'color': '255,0,0', 'size': '2'}), "Grundzentrum"],
        ]
        for category in categories:
            value = category[0]
            symbol = category[1]
            label = category[2]
            
            cat = QgsRendererCategory(value, symbol, label)
            renderer.addCategory(cat)
        
        return renderer

    @staticmethod
    def loadFromFile(filePath: str, layerName):
        layer = QgsVectorLayer(filePath, layerName, "ogr")
        return CenterLayer(layer)
    

    def qgsLayer(self):
        return self._layer
    
    def name(self):
        return self._layer.name()